"""PageUp People Applicant Bulk Compile parser.

A bulk compile is one PDF holding many applicants, generated by PageUp. Its
structure is declared by the file itself, on a cover page that states which
attachment types were compiled and lists exactly who is included::

    PageUp People Applicant Bulk Compile
    The following document types are provided for each applicant
    Resume
    The following applicants are included in this document
    Peter Aguila
    ...
    Number of Applicants: 14

After that cover page the file repeats, once per applicant::

    <Applicant Name>
    Primary application form - ...        <- application report starts
    ...
    Total score                           <- application report's last page
    <attachment pages>                    <- the compiled attachment(s)
    <next applicant name>                 <- next packet starts

Every boundary in that shape is stated by the file, so extraction is exact:
no interior page's appearance has to be judged. Crucially the cover page is
*metadata* -- it describes the file rather than belonging to any applicant --
so it is never exported into anybody's documents.

The one thing not stated outright is which attachment is which when several
types were compiled. With a single declared type the attachment region is that
type by construction and is never divided -- the file has already answered the
question, and a resume's later pages carry enough contact details and section
headings to fool a splitter into cutting real resumes in half.

With several declared types that region holds several documents run together,
and dividing it is the parser's job. It divides on what the file states before
what a page merely looks like: an uploaded attachment's own filename, a printed
document title naming a different type, a restart of page numbering, and only
then the shape of the text. Where none of that appears the pages stay together
and, if they read as more than one declared type, go to review -- a document
the reviewer is told to check beats one silently exported under the wrong name.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass, field

from app.models.candidate import Candidate, CREDENTIALS, normalize_person_name
from app.models.enums import SeparatorPolicy, SeparatorState
from app.models.page import PageAnalysis
from app.profiles.base import OTHER, DocumentProfile
from app.profiles.recruiting import APPLICATION_REPORT, RESUME
from app.services.parsers.attachments import AttachmentDetector
from app.services.parsers.base import ParseOutcome, ParserMatch, assign_page
from app.services.text_features import PageFeatures, flatten

#: The bulk compile's own title. Nothing else prints this.
TITLE_MARKER = "pageup people applicant bulk compile"
#: Introduces the list of compiled attachment types.
TYPES_MARKER = "the following document types are provided for each applicant"
#: Introduces the applicant roster.
ROSTER_MARKER = "the following applicants are included in this document"
#: Precedes the declared applicant count.
COUNT_MARKER = "number of applicants"
#: Heading that opens an applicant's generated application form.
APPLICATION_FORM_MARKER = "primary application form"
#: Last line of an applicant's application form.
APPLICATION_END_MARKER = "total score"

#: How far into a page to look for the application-form heading and name.
_HEADER_LINES = 10
#: A resume identity belongs in its compact header, before body sections begin.
_RESUME_HEADER_LINES = 8
#: Minimum evidence for an ordered roster identity to open the next resume.
_STRONG_RESUME_HEADER_SCORE = 0.85

_RESUME_SECTION_HEADINGS = frozenset(
    {
        "career history",
        "core competencies",
        "education",
        "employment",
        "employment history",
        "experience",
        "professional experience",
        "professional references",
        "references",
        "skills",
        "work experience",
    }
)
_HEADER_PROSE_TOKENS = frozenset(
    {
        "and",
        "director",
        "for",
        "manager",
        "of",
        "reference",
        "references",
        "the",
        "with",
        "worked",
    }
)

#: Evidence a single page needs before it counts as clearly being one declared
#: type rather than another. Used only to decide whether an *unsplit* region
#: was hiding several documents, so the bar is set where a page reads
#: unmistakably as one thing -- a weak signal here would flag whole batches.
_CLEAR_PAGE_SCORE = 4.0
_CLEAR_PAGE_MARGIN = 2.0

_COUNT_RE = re.compile(r"(?i)number\s+of\s+applicants\s*[:\-]?\s*(\d{1,4})")
_PARENTHETICAL_RE = re.compile(r"\([^)]*\)")

#: Honorifics that decorate a roster name without identifying anybody.
_TITLES = frozenset({"dr", "mr", "mrs", "ms", "miss", "prof", "professor", "rev", "sir", "dame"})


def roster_key(name: str) -> str:
    """Normalized identity for matching a roster entry to a form heading.

    The roster prints a display name that may carry an honorific and a
    preferred name -- ``Dr Tandalea Mercer (Tandalea)`` -- while the generated
    form heading prints a plainer ``Tandalea Mercer``. Both reduce to the same
    key so the two are recognised as one person, without the display name
    losing anything the user would want to see on their file.
    """
    text = _PARENTHETICAL_RE.sub(" ", name or "")
    text = re.sub(r"[-‐‑‒–—]", " ", text)
    normalized = _fold_identity(normalize_person_name(text))
    parts = [part for part in normalized.split() if part not in _TITLES]
    return " ".join(parts)


@dataclass(frozen=True)
class RosterEntry:
    """One applicant named on the bulk cover page."""

    display_name: str
    key: str
    given_names: frozenset[str] = field(default_factory=frozenset)
    surname: str = ""

    @classmethod
    def build(cls, display_name: str) -> "RosterEntry":
        key = roster_key(display_name)
        parts = key.split()
        preferred: set[str] = set()
        for parenthetical in re.findall(r"\(([^)]*)\)", display_name or ""):
            preferred.update(_identity_tokens(parenthetical))
        given_names = set(parts[:-1]) | preferred
        return cls(
            display_name=display_name.strip(),
            key=key,
            given_names=frozenset(given_names),
            surname=(
                parts[-1]
                if len(parts) >= 2
                else parts[0]
                if parts and preferred
                else ""
            ),
        )


@dataclass
class BulkCover:
    """Everything the cover page declares about the file."""

    page_index: int = 0
    declared_types: list[str] = field(default_factory=list)
    roster: list[RosterEntry] = field(default_factory=list)
    declared_count: int | None = None

    def match(self, name: str) -> RosterEntry | None:
        key = roster_key(name)
        if not key:
            return None
        for entry in self.roster:
            if entry.key == key:
                return entry
        return None


class PageUpBulkCompileParser:
    """Deterministic parser for PageUp People Applicant Bulk Compile exports."""

    name = "PageUp bulk compile"

    def __init__(self, profile: DocumentProfile) -> None:
        self.profile = profile
        self.attachments = AttachmentDetector(profile)

    # ------------------------------------------------------------------
    def can_parse(self, features_list: list[PageFeatures]) -> ParserMatch:
        """Match on the bulk compile's own cover page.

        The title alone is close to conclusive -- it is a product's own banner,
        not a phrase a resume contains -- but the roster and applicant-count
        markers are checked too so a file merely *mentioning* PageUp does not
        get parsed as one.
        """
        if not features_list:
            return ParserMatch.no()

        # The cover is the first page in every real export; a couple of pages
        # of slack costs nothing and tolerates a prepended banner sheet.
        for features in features_list[:3]:
            flat = features.flat
            if TITLE_MARKER in flat:
                supporting = sum(
                    1 for marker in (TYPES_MARKER, ROSTER_MARKER, COUNT_MARKER) if marker in flat
                )
                if supporting:
                    return ParserMatch(0.99, "PageUp bulk compile cover page")
                return ParserMatch(0.80, "PageUp bulk compile title")
            if ROSTER_MARKER in flat and COUNT_MARKER in flat:
                return ParserMatch(0.75, "PageUp-style applicant roster cover page")
        return ParserMatch.no()

    # ------------------------------------------------------------------
    def parse(
        self,
        pages: list[PageAnalysis],
        features_list: list[PageFeatures],
        *,
        separator_policy: SeparatorPolicy,
    ) -> ParseOutcome:
        outcome = ParseOutcome(parser=self.name)
        cover = self._parse_cover(features_list)

        outcome.metadata["declared_types"] = list(cover.declared_types)
        outcome.metadata["declared_count"] = cover.declared_count
        outcome.metadata["roster"] = [entry.display_name for entry in cover.roster]

        if not cover.roster:
            outcome.warn(
                "The PageUp cover page listed no applicants, so every boundary "
                "here was found from the application forms alone."
            )
        if cover.declared_count is not None and cover.declared_count != len(cover.roster):
            outcome.warn(
                f"The cover page says {cover.declared_count} applicants but lists "
                f"{len(cover.roster)}. Check nothing is missing."
            )

        self._mark_cover_page(pages, features_list, cover, separator_policy)
        if self._is_resume_only(cover, features_list):
            outcome.metadata["mode"] = "resume_only"
            segments = self._walk_resume_only(pages, features_list, cover, outcome)
        else:
            outcome.metadata["mode"] = "application_forms"
            segments = self._walk(pages, features_list, cover, outcome)
            segments = self._split_attachments(segments, features_list, cover, outcome)
        self._apply(pages, features_list, segments, cover, outcome)

        found = len({segment.candidate_key for segment in segments if segment.candidate_key})
        outcome.metadata["applicants_found"] = found
        if cover.declared_count is not None and found and found != cover.declared_count:
            outcome.warn(
                f"The cover page says {cover.declared_count} applicants but "
                f"{found} were found in the file."
            )
        return outcome

    # ------------------------------------------------------------------
    # Cover page
    # ------------------------------------------------------------------
    def _parse_cover(self, features_list: list[PageFeatures]) -> BulkCover:
        for index, features in enumerate(features_list[:3]):
            flat = features.flat
            if TITLE_MARKER in flat or (ROSTER_MARKER in flat and COUNT_MARKER in flat):
                return self._read_cover(index, features)
        return BulkCover(page_index=-1)

    def _read_cover(self, page_index: int, features: PageFeatures) -> BulkCover:
        cover = BulkCover(page_index=page_index)
        lines = [line.strip() for line in features.lines if line.strip()]

        types_at = _index_of(lines, TYPES_MARKER)
        roster_at = _index_of(lines, ROSTER_MARKER)
        count_at = _index_of(lines, COUNT_MARKER)

        if types_at is not None:
            end = roster_at if roster_at is not None else len(lines)
            cover.declared_types = self._declared_types(lines[types_at + 1 : end])

        if roster_at is not None:
            end = count_at if count_at is not None else len(lines)
            cover.roster = [
                RosterEntry.build(line)
                for line in lines[roster_at + 1 : end]
                if _looks_like_roster_name(line)
            ]

        match = _COUNT_RE.search(features.text)
        if match:
            cover.declared_count = int(match.group(1))
            if len(cover.roster) > cover.declared_count:
                # Some PageUp cover templates place generic footer lines
                # between the roster and the printed count. The declared count
                # is authoritative, and the actual roster is the ordered block
                # immediately following its heading.
                cover.roster = cover.roster[: cover.declared_count]
        return cover

    def _declared_types(self, lines: list[str]) -> list[str]:
        """Canonical document types the cover says were compiled."""
        types: list[str] = []
        for line in lines:
            canonical = self.profile.normalize_type(line)
            if canonical != OTHER and canonical not in types:
                types.append(canonical)
        return types

    def _mark_cover_page(
        self,
        pages: list[PageAnalysis],
        features_list: list[PageFeatures],
        cover: BulkCover,
        separator_policy: SeparatorPolicy,
    ) -> None:
        """The cover describes the file, so it belongs to no applicant.

        Excluded unconditionally, *not* according to the separator policy. That
        setting decides what to do with a divider page inside somebody's
        packet -- a sheet reading only "Resume" that a user might reasonably
        want kept. The bulk cover is a different thing entirely: it is the
        file's own manifest, listing every applicant in the batch. Letting a
        global preference put it inside one applicant's resume would leak the
        other thirteen names into their document.
        """
        if cover.page_index < 0 or cover.page_index >= len(pages):
            return
        page = pages[cover.page_index]
        page.predicted_type = OTHER
        page.separator_label = "PageUp bulk compile cover"
        page.separator_state = SeparatorState.EXCLUDED
        page.excluded = True
        assign_page(
            page,
            OTHER,
            Candidate(),
            starts_new_document=True,
            parser_name=self.name,
            reason="bulk compile cover page (file metadata, not an applicant's document)",
        )

    # ------------------------------------------------------------------
    # Structure walk
    # ------------------------------------------------------------------
    def _is_resume_only(
        self, cover: BulkCover, features_list: list[PageFeatures]
    ) -> bool:
        """Whether the cover declares the roster-ordered resume-only shape."""
        if cover.declared_types != [RESUME] or not cover.roster:
            return False
        return not any(
            APPLICATION_FORM_MARKER in features.flat
            for index, features in enumerate(features_list)
            if index != cover.page_index
        )

    def _walk_resume_only(
        self,
        pages: list[PageAnalysis],
        features_list: list[PageFeatures],
        cover: BulkCover,
        outcome: ParseOutcome,
    ) -> list["_Segment"]:
        """Split roster-ordered resumes using only the next expected identity.

        A roster member mentioned in an earlier resume is not a boundary. The
        expected identity must occur in a compact first-page header, before a
        body section, with resume/contact layout support. If that evidence is
        absent, the open resume keeps the remaining pages and goes to review;
        no page is silently assigned across an invented split.
        """
        content_indexes = [
            index
            for index, page in enumerate(pages)
            if index != cover.page_index and not page.error
        ]
        if not content_indexes:
            return []

        first_content = content_indexes[0]
        last_content = content_indexes[-1]
        first_entry = cover.roster[0]
        first_start = self._find_resume_start(
            first_entry, features_list, first_content, last_content
        )

        if first_start is None:
            segment = _Segment(
                kind="attachment",
                document_type=RESUME,
                display_name="",
                candidate_key="",
                first_page=first_content,
                last_page=last_content,
            )
            self._flag_missing_resume_boundary(segment, outcome)
            return [segment]

        segments: list[_Segment] = []
        if first_start > first_content:
            leading = _Segment(
                kind="attachment",
                document_type=RESUME,
                display_name="",
                candidate_key="",
                first_page=first_content,
                last_page=first_start - 1,
            )
            self._flag_missing_resume_boundary(leading, outcome)
            segments.append(leading)

        current = _Segment(
            kind="attachment",
            document_type=RESUME,
            display_name=first_entry.display_name,
            candidate_key=first_entry.key,
            first_page=first_start,
            last_page=last_content,
        )
        segments.append(current)

        for expected in cover.roster[1:]:
            boundary = self._find_resume_start(
                expected,
                features_list,
                current.first_page + 1,
                last_content,
            )
            if boundary is None:
                current.last_page = last_content
                self._flag_missing_resume_boundary(current, outcome)
                break

            current.last_page = boundary - 1
            current = _Segment(
                kind="attachment",
                document_type=RESUME,
                display_name=expected.display_name,
                candidate_key=expected.key,
                first_page=boundary,
                last_page=last_content,
            )
            segments.append(current)

        return segments

    def _find_resume_start(
        self,
        expected: RosterEntry,
        features_list: list[PageFeatures],
        first_page: int,
        last_page: int,
    ) -> int | None:
        """Find the first strong header for exactly one expected roster entry."""
        for index in range(max(first_page, 0), min(last_page + 1, len(features_list))):
            if self._resume_header_score(expected, features_list[index]) >= (
                _STRONG_RESUME_HEADER_SCORE
            ):
                return index
        return None

    def _resume_header_score(
        self, expected: RosterEntry, features: PageFeatures
    ) -> float:
        """Strength of the expected identity as a resume first-page header."""
        if not expected.surname or not expected.given_names:
            return 0.0
        if features.page_marker and features.page_marker[0] > 1:
            return 0.0

        resume_layout = self._has_resume_first_page_layout(features)
        section_seen = False
        best = 0.0
        for position, line in enumerate(features.first_lines[:_RESUME_HEADER_LINES]):
            normalized_line = flatten(line).strip().rstrip(":")
            if normalized_line in _RESUME_SECTION_HEADINGS:
                section_seen = True
                continue
            if section_seen:
                continue

            identity = _header_identity_strength(expected, line)
            if identity <= 0:
                continue
            positional = 0.20 if position == 0 else 0.12 if position <= 2 else 0.06
            contact = 0.12 if features.has_contact_block else 0.0
            layout = 0.12 if resume_layout else 0.0
            best = max(best, identity + positional + contact + layout)
        return min(best, 1.0)

    def _has_resume_first_page_layout(self, features: PageFeatures) -> bool:
        headings = {flatten(heading).strip().rstrip(":") for heading in features.heading_lines}
        has_resume_heading = bool(headings & (_RESUME_SECTION_HEADINGS - {"references"}))
        return bool(
            features.has_contact_block
            or has_resume_heading
            or (features.bullet_lines and features.date_range_count)
            or (features.date_range_count >= 2 and features.line_count >= 12)
        )

    def _flag_missing_resume_boundary(
        self, segment: "_Segment", outcome: ParseOutcome
    ) -> None:
        reason = "Could not confidently locate the next applicant Resume boundary."
        segment.flag(reason)
        outcome.warn(reason)

    def _walk(
        self,
        pages: list[PageAnalysis],
        features_list: list[PageFeatures],
        cover: BulkCover,
        outcome: ParseOutcome,
    ) -> list["_Segment"]:
        """Split the file into application and attachment segments."""
        segments: list[_Segment] = []
        current: _Segment | None = None
        application_closed = False

        for index, features in enumerate(features_list):
            if index == cover.page_index or pages[index].error:
                continue

            entry = self._application_start(features, cover)
            # The form heading repeats as a running header on continuation
            # pages, so its presence alone does not open a packet -- only a
            # change of applicant does. Keying the boundary on identity rather
            # than on the heading is also what makes the parser robust to
            # however a given export decorates its pages.
            if entry is not None and (
                current is None or entry.key != current.candidate_key
            ):
                current = _Segment(
                    kind="application",
                    document_type=APPLICATION_REPORT,
                    display_name=entry.display_name,
                    candidate_key=entry.key,
                    first_page=index,
                    last_page=index,
                )
                segments.append(current)
                application_closed = False
                continue

            if current is None:
                # Pages before the first recognised applicant. Left for the
                # generic pipeline rather than attributed to nobody.
                continue

            if not application_closed:
                current.last_page = index
                if APPLICATION_END_MARKER in features.flat:
                    application_closed = True
                continue

            if current.kind == "application":
                current = _Segment(
                    kind="attachment",
                    document_type=None,
                    display_name=current.display_name,
                    candidate_key=current.candidate_key,
                    first_page=index,
                    last_page=index,
                )
                segments.append(current)
            else:
                current.last_page = index

        for segment in segments:
            if segment.kind == "application" and not self._closed(
                segment, features_list
            ):
                outcome.warn(
                    f"{segment.display_name}'s application form has no “Total score” "
                    "ending, so where their attachments begin is a guess."
                )
        return segments

    def _closed(self, segment: "_Segment", features_list: list[PageFeatures]) -> bool:
        return any(
            APPLICATION_END_MARKER in features_list[index].flat
            for index in range(segment.first_page, segment.last_page + 1)
            if index < len(features_list)
        )

    def _application_start(
        self, features: PageFeatures, cover: BulkCover
    ) -> RosterEntry | None:
        """A roster name printed above a generated application-form heading."""
        head = features.first_lines[:_HEADER_LINES]
        if not any(APPLICATION_FORM_MARKER in flatten(line) for line in head):
            return None

        for line in head:
            entry = cover.match(line)
            if entry is not None:
                return entry

        # The roster is missing or disagrees; the form heading alone still
        # marks a packet boundary, and the name above it is the authority.
        for line in head:
            if APPLICATION_FORM_MARKER in flatten(line):
                break
            key = roster_key(line)
            if key and len(key.split()) >= 2:
                return RosterEntry.build(line)
        return None

    # ------------------------------------------------------------------
    # Attachment region
    # ------------------------------------------------------------------
    def _split_attachments(
        self,
        segments: list["_Segment"],
        features_list: list[PageFeatures],
        cover: BulkCover,
        outcome: ParseOutcome,
    ) -> list["_Segment"]:
        """Turn each applicant's attachment region into its logical documents.

        The walk gives one region per applicant -- everything between "Total
        score" and the next applicant. When the cover compiled a single
        attachment type that region *is* one document, stated by the file. When
        it compiled several, the region holds several documents run together
        and has to be divided.
        """
        expanded: list[_Segment] = []
        for segment in segments:
            if segment.kind != "attachment":
                expanded.append(segment)
                continue
            expanded.extend(self._split_region(segment, features_list, cover, outcome))
        return expanded

    def _split_region(
        self,
        region: "_Segment",
        features_list: list[PageFeatures],
        cover: BulkCover,
        outcome: ParseOutcome,
    ) -> list["_Segment"]:
        """Divide one applicant's attachment region into documents."""
        declared = cover.declared_types

        # One declared type: the cover has already answered the question, and
        # any split would be this parser second-guessing the file that
        # generated it. A resume's later pages can carry contact details and
        # section headings; dividing on those would cut real resumes in half.
        if len(declared) == 1:
            region.document_type = declared[0]
            return [region]

        opening = self._opening_type(features_list, region.first_page)
        parts: list[_Segment] = [self._part(region, region.first_page, opening)]
        for index in range(region.first_page + 1, region.last_page + 1):
            if index >= len(features_list):
                break
            boundary = self._attachment_boundary(features_list, index, parts[-1].document_type)
            if boundary is None:
                parts[-1].last_page = index
                continue
            part = self._part(region, index, boundary.document_type)
            part.flag(boundary.review_reason)
            parts.append(part)

        for part in parts:
            if part.document_type is None:
                part.document_type = self._classify_part(
                    part, features_list, declared, outcome
                )
            else:
                self._check_declared(part, declared, outcome)

        if len(parts) == 1:
            self._check_merged(parts[0], features_list, declared, outcome)
        return parts

    def _part(self, region: "_Segment", first_page: int, document_type: str | None) -> "_Segment":
        return _Segment(
            kind="attachment",
            document_type=document_type,
            display_name=region.display_name,
            candidate_key=region.candidate_key,
            first_page=first_page,
            last_page=first_page,
        )

    def _opening_type(self, features_list: list[PageFeatures], index: int) -> str | None:
        """The type the region's own first page names, if it names one."""
        if index >= len(features_list):
            return None
        features = features_list[index]
        return (
            self.attachments.filename_type(features)
            or self.attachments.title_type(features)
            or self.attachments.opening(features, None)
        )

    def _attachment_boundary(
        self, features_list: list[PageFeatures], index: int, open_type: str | None
    ) -> "_Boundary | None":
        """Whether a new uploaded document starts on this page.

        Ordered so that what the file *states* outranks what the page looks
        like: the applicant's own filename first, then a printed document
        title, then a restart of page numbering, and only then the shape of the
        text. A page that says nothing continues whatever is open, because a
        sparse or unremarkable page is not evidence of anything.
        """
        features = features_list[index]
        previous = features_list[index - 1] if index else None

        named = self.attachments.filename_type(features)
        if named is not None:
            return _Boundary(named)

        # A running header repeats the document's title on its continuation
        # pages, so a printed title only opens something when it names a
        # *different* type from the one already running.
        titled = self.attachments.title_type(features)
        if titled is not None and titled != open_type:
            return _Boundary(titled)

        if self.attachments.is_continuation_page(features):
            return None

        if self.attachments.restarts_numbering(features, previous):
            # The document numbered its own pages back to one. That is a
            # boundary the file states, even though it says nothing about what
            # kind of document is starting -- so the type is left open and
            # classified from the pages themselves.
            return _Boundary(self.attachments.opening(features, open_type))

        opening = self.attachments.opening(features, open_type)
        if opening is not None and opening != open_type:
            return _Boundary(opening)
        return None

    def _check_declared(
        self, part: "_Segment", declared: list[str], outcome: ParseOutcome
    ) -> None:
        """Flag an attachment whose type the cover page never promised."""
        if not declared or part.document_type is None:
            return
        if part.document_type in declared:
            return
        part.flag(
            f"This looks like a {part.document_type.lower()}, but the cover page "
            f"only lists {_join(declared)}."
        )
        outcome.warn(
            f"{part.display_name} has an attachment the cover page did not list."
        )

    def _check_merged(
        self,
        part: "_Segment",
        features_list: list[PageFeatures],
        declared: list[str],
        outcome: ParseOutcome,
    ) -> None:
        """Catch several documents that could not be told apart.

        The cover says more than one type was compiled, yet no boundary was
        found inside the region. Either the applicant uploaded only one of
        them -- normal, and not something to invent a second document over --
        or two documents ran together without any of the evidence a split
        needs. When the pages themselves point at more than one declared type,
        it is the second case, and that belongs in review rather than being
        exported as one mislabelled document.
        """
        winners = {
            winner
            for index in range(part.first_page, part.last_page + 1)
            if index < len(features_list)
            for winner in (self._page_winner(features_list[index], declared),)
            if winner
        }
        if len(winners) < 2:
            return
        part.flag(
            f"These pages look like more than one document ({_join(sorted(winners))}), "
            "but nothing in the file says where one ends and the next begins."
        )
        outcome.warn(
            f"{part.display_name}'s attachments could not be separated and need review."
        )

    def _page_winner(self, features: PageFeatures, declared: list[str]) -> str | None:
        """The declared type one page clearly reads as, if any."""
        scores = {
            name: score
            for name, score in self.profile.score_page(features).items()
            if name in declared
        }
        if not scores:
            return None
        ranked = sorted(scores.items(), key=lambda item: item[1], reverse=True)
        best_type, best_score = ranked[0]
        runner_up = ranked[1][1] if len(ranked) > 1 else 0.0
        if best_score < _CLEAR_PAGE_SCORE or best_score - runner_up < _CLEAR_PAGE_MARGIN:
            return None
        return best_type

    # ------------------------------------------------------------------
    # Assignment
    # ------------------------------------------------------------------
    def _apply(
        self,
        pages: list[PageAnalysis],
        features_list: list[PageFeatures],
        segments: list["_Segment"],
        cover: BulkCover,
        outcome: ParseOutcome,
    ) -> None:
        for segment in segments:
            candidate = Candidate(name=segment.display_name or None)
            outcome.documents_found += 1
            for index in range(segment.first_page, segment.last_page + 1):
                if index >= len(pages) or pages[index].error:
                    continue
                assign_page(
                    pages[index],
                    segment.document_type,
                    candidate,
                    starts_new_document=index == segment.first_page,
                    parser_name=self.name,
                    reason=(
                        f"{segment.display_name}'s {segment.document_type.lower()}"
                        if index == segment.first_page and segment.display_name
                        else "resume-only bulk section needs applicant review"
                        if index == segment.first_page
                        else "continues open section"
                    ),
                )
            for reason in segment.review_reasons:
                pages[segment.first_page].add_review_reason(reason)

    def _classify_part(
        self,
        part: "_Segment",
        features_list: list[PageFeatures],
        declared: list[str],
        outcome: ParseOutcome,
    ) -> str:
        """Name an attachment that nothing structural identified.

        Reached only when the file said nothing about this upload -- no
        filename, no title, no numbering -- so the answer has to come from the
        text, and the bar for accepting it is deliberately high. Every other
        attachment here was named by the file; one that has to be inferred is
        the one worth doubting, and a wrong name sends a cover letter into the
        resume folder where nobody will look for it. Below the bar the pages
        are still exported, still attributed to the right applicant, and
        flagged for a human to type.
        """
        text = "\n".join(
            features_list[index].text
            for index in range(part.first_page, part.last_page + 1)
            if index < len(features_list)
        )
        from app.services.text_features import extract_features

        scores = self.profile.score_page(extract_features(text))
        if declared:
            scores = {name: score for name, score in scores.items() if name in declared}
        ranked = sorted(scores.items(), key=lambda item: item[1], reverse=True)

        if not ranked or ranked[0][1] <= 0:
            part.flag("This attachment could not be identified from the file's structure.")
            outcome.warn(f"{part.display_name}'s attachment could not be identified.")
            return OTHER

        best_type, best_score = ranked[0]
        runner_up = ranked[1][1] if len(ranked) > 1 else 0.0
        if best_score < _CLEAR_PAGE_SCORE or best_score - runner_up < _CLEAR_PAGE_MARGIN:
            runner_up_name = ranked[1][0].lower() if len(ranked) > 1 else "something else"
            part.flag(
                f"Nothing in the file names this attachment. It reads most like a "
                f"{best_type.lower()}, but {runner_up_name} is close enough that it "
                "needs checking."
            )
            outcome.warn(f"{part.display_name}'s attachment type was not clear-cut.")
        return best_type


@dataclass
class _Segment:
    """One contiguous run of pages belonging to one applicant's document."""

    kind: str  # "application" | "attachment"
    document_type: str | None
    display_name: str
    candidate_key: str
    first_page: int
    last_page: int
    review_reasons: list[str] = field(default_factory=list)

    def flag(self, reason: str) -> None:
        """Record why a human should look at this document."""
        if reason and reason not in self.review_reasons:
            self.review_reasons.append(reason)


@dataclass(frozen=True)
class _Boundary:
    """A new attachment starting, and the type it declares if it declares one."""

    document_type: str | None = None
    review_reason: str = ""


def _fold_identity(text: str) -> str:
    """Case/diacritic/punctuation-insensitive text used only for identity matching."""
    decomposed = unicodedata.normalize("NFKD", text or "")
    without_marks = "".join(
        character
        for character in decomposed
        if not unicodedata.combining(character)
    )
    separated = re.sub(r"[-‐‑‒–—]", " ", without_marks.casefold())
    cleaned = "".join(
        character
        for character in separated
        if character.isalnum() or character.isspace()
    )
    return " ".join(cleaned.split())


def _identity_tokens(text: str) -> tuple[str, ...]:
    """Identity words with honorifics and credential suffixes removed."""
    credentials = {_fold_identity(value).replace(" ", "") for value in CREDENTIALS}
    return tuple(
        token
        for token in _fold_identity(text).split()
        if token not in _TITLES and token.replace(" ", "") not in credentials
    )


def _header_identity_strength(entry: RosterEntry, line: str) -> float:
    """Match a compact header line, rejecting prose that merely names somebody."""
    # Multi-column PDFs sometimes extract ``Given email@example.test Surname``
    # as one line. Remove the contact token in place rather than truncating at
    # ``@``, which would throw away whichever name column was extracted later.
    without_email = re.sub(r"\S+@\S+", " ", line or "")
    header = re.split(r"\s+[|•●▪]\s+", without_email, maxsplit=1)[0]
    tokens = list(_identity_tokens(header))
    if not tokens or len(tokens) > 8:
        return 0.0
    if entry.surname not in tokens:
        return 0.0

    known = set(entry.key.split()) | set(entry.given_names)
    extras = [token for token in tokens if token not in known]
    if set(extras) & _HEADER_PROSE_TOKENS:
        return 0.0

    given_match = any(given in tokens for given in entry.given_names)
    if not given_match:
        # Strict fallback for a resume that uses an undeclared preferred name:
        # surname plus one compact header line. Its lower score means this can
        # only become a boundary at the top of a page with both contact and
        # resume-layout evidence.
        return 0.42 if len(tokens) <= 4 else 0.0
    if not extras:
        return 0.60
    if len(extras) <= 3:
        # A resume may spell out a middle name where the roster used an
        # initial, or carry a credential suffix not in the common list.
        return 0.54
    return 0.0


def _join(names: list[str]) -> str:
    """``a, b and c`` -- for messages a reviewer reads."""
    if not names:
        return ""
    if len(names) == 1:
        return names[0]
    return f"{', '.join(names[:-1])} and {names[-1]}"


def _index_of(lines: list[str], marker: str) -> int | None:
    for index, line in enumerate(lines):
        if marker in flatten(line):
            return index
    return None


def _looks_like_roster_name(line: str) -> bool:
    """A roster line that names a person rather than a heading or a count."""
    text = line.strip()
    if not (2 <= len(text) <= 80):
        return False
    if _COUNT_RE.search(text):
        return False
    if any(character.isdigit() for character in text):
        return False
    return bool(roster_key(text))


__all__ = [
    "PageUpBulkCompileParser",
    "BulkCover",
    "RosterEntry",
    "roster_key",
    "TITLE_MARKER",
    "ROSTER_MARKER",
    "APPLICATION_FORM_MARKER",
    "APPLICATION_END_MARKER",
]
