"""Shared PyInstaller configuration for the installed and portable builds.

Both builds come from the same analysis settings so they cannot drift apart.
The difference is only how they are assembled:

* **Installed build** (``SmartPDFSorter.spec``) -- onedir. Starts fast, extracts
  nothing at run time, and is what the MSI installs.
* **Portable build** (``SmartPDFSorter-Portable.spec``) -- onefile. One EXE to
  copy onto a machine, at the cost of unpacking to a temporary directory on
  every launch.
"""

from __future__ import annotations

import sys
from pathlib import Path

APP_NAME = "SmartPDFSorter"
DISPLAY_NAME = "Smart PDF Sorter"
PUBLISHER = "Smart PDF Sorter"


def repo_root(spec_path: str) -> Path:
    return Path(spec_path).resolve()


def read_version(root: Path) -> str:
    """Read the version from app/version.py without importing the app."""
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))
    from app.version import __version__

    return __version__


def data_files(root: Path) -> list[tuple[str, str]]:
    """Assets bundled into both builds."""
    datas: list[tuple[str, str]] = []
    for asset in ("icon.png", "icon.ico"):
        path = root / "assets" / asset
        if path.exists():
            datas.append((str(path), "assets"))
    return datas


def hidden_imports() -> list[str]:
    """Imports PyInstaller's static analysis cannot see.

    ``keyring`` picks its backend at run time, so without these the packaged
    build silently loses credential storage and the OpenAI key cannot be saved.
    """
    from PyInstaller.utils.hooks import collect_submodules

    return [
        "keyring.backends.Windows",
        "keyring.backends.SecretService",
        "keyring.backends.macOS",
        "keyring.backends.fail",
        "keyring.backends.chainer",
        *collect_submodules("app"),
    ]


def excludes() -> list[str]:
    """Qt and scientific-stack modules the application never touches.

    Excluding them keeps the download small and, importantly, avoids shipping a
    browser engine inside a PDF utility.
    """
    return [
        "PySide6.QtWebEngineCore",
        "PySide6.QtWebEngineWidgets",
        "PySide6.QtWebEngineQuick",
        "PySide6.QtQuick",
        "PySide6.QtQuick3D",
        "PySide6.QtQml",
        "PySide6.QtMultimedia",
        "PySide6.QtMultimediaWidgets",
        "PySide6.Qt3DCore",
        "PySide6.Qt3DRender",
        "PySide6.QtCharts",
        "PySide6.QtDataVisualization",
        "PySide6.QtBluetooth",
        "PySide6.QtNfc",
        "PySide6.QtPositioning",
        "PySide6.QtSql",
        "PySide6.QtTest",
        "PySide6.QtDesigner",
        "shiboken6.support",
        "tkinter",
        "matplotlib",
        "numpy",
        "scipy",
        "pandas",
        "IPython",
        "pytest",
        "_pytest",
        "pefile",
    ]


def icon_path(root: Path) -> str | None:
    icon = root / "assets" / "icon.ico"
    return str(icon) if icon.exists() else None


def write_version_resource(root: Path, version: str, *, portable: bool) -> str | None:
    """Generate the Windows version resource so the EXE has real metadata.

    Without this the file shows blank Details in Explorer, which looks
    unfinished and makes deployment tooling harder to audit.
    """
    if not sys.platform.startswith("win"):
        return None

    parts = [int(piece) for piece in version.split(".")[:3]]
    while len(parts) < 4:
        parts.append(0)
    filevers = tuple(parts[:4])

    description = (
        f"{DISPLAY_NAME} (portable)" if portable else DISPLAY_NAME
    )
    original_filename = (
        f"{APP_NAME}-Portable.exe" if portable else f"{APP_NAME}.exe"
    )

    content = f"""# Generated by packaging/pyinstaller_common.py -- do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers},
    prodvers={filevers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', '{PUBLISHER}'),
         StringStruct('FileDescription', '{description}'),
         StringStruct('FileVersion', '{version}'),
         StringStruct('InternalName', '{APP_NAME}'),
         StringStruct('LegalCopyright', 'See THIRD_PARTY_NOTICES.md'),
         StringStruct('OriginalFilename', '{original_filename}'),
         StringStruct('ProductName', '{DISPLAY_NAME}'),
         StringStruct('ProductVersion', '{version}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    output_dir = root / "build"
    output_dir.mkdir(parents=True, exist_ok=True)
    suffix = "portable" if portable else "installed"
    destination = output_dir / f"version_info_{suffix}.txt"
    destination.write_text(content, encoding="utf-8")
    return str(destination)


__all__ = [
    "APP_NAME",
    "DISPLAY_NAME",
    "PUBLISHER",
    "read_version",
    "data_files",
    "hidden_imports",
    "excludes",
    "icon_path",
    "write_version_resource",
]
